# Generated by Django 5.2.8 on 2025-12-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_full_name_account_phone_account_user_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
