# Generated by Django 5.2.7 on 2025-11-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
