# Generated by Django 5.2.8 on 2025-11-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_categories_user_created_categories_user_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
