# Generated by Django 5.2.7 on 2025-12-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
